"use client";

import { useEffect, useRef, useState } from "react";
import { useSearchParams } from "next/navigation";
import { LoadingScreen } from "@/components/loading-screen";
import { Onboarding } from "./onboarding";
import { mockData, type OnboardingData } from "@/lib/mock";

const API_URL = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000";

type FetchState =
  | { status: "loading" }
  | { status: "done"; data: OnboardingData }
  | { status: "error"; message: string };

export function OnboardingFlow() {
  const params = useSearchParams();
  const slug = params.get("repo")?.trim() || "supabase/supabase";
  const [animDone, setAnimDone] = useState(false);
  const [fetchState, setFetchState] = useState<FetchState>({ status: "loading" });

  // Keep a stable ref so the effect doesn't re-run on re-renders
  const slugRef = useRef(slug);
  slugRef.current = slug;

  useEffect(() => {
    const [owner, name] = slugRef.current.split("/");

    fetch(`${API_URL}/explain`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ url: `https://github.com/${slugRef.current}` }),
    })
      .then((r) => {
        if (!r.ok) return r.json().then((e) => Promise.reject(e?.detail ?? `Error ${r.status}`));
        return r.json();
      })
      .then((json) => {
        const data: OnboardingData = {
          // Fields returned by the backend
          whatItDoes: json.whatItDoes ?? [],
          whyItExists: json.whyItExists ?? mockData.whyItExists,
          beforeYouDive: json.beforeYouDive ?? [],
          keyFiles: json.keyFiles ?? [],
          folders: json.folders ?? [],
          technologies: json.technologies ?? [],
          confusions: json.confusions ?? [],
          ifIJoined: json.ifIJoined ?? mockData.ifIJoined,

          // Repo header — prefer backend-injected metadata, fall back to slug
          repo: json._repo ?? {
            owner: owner ?? "",
            name: name ?? "",
            url: `https://github.com/${slugRef.current}`,
            tagline: json.oneLiner ?? "",
            stars: "—",
            language: "—",
          },

          // Not yet generated by the backend — use mock placeholders
          architecture: mockData.architecture,
          requestFlow: mockData.requestFlow,
          video: mockData.video,
        };
        setFetchState({ status: "done", data });
      })
      .catch((err) => {
        setFetchState({ status: "error", message: String(err) });
      });
  }, []);

  // Show error immediately — no point waiting for the animation
  if (fetchState.status === "error") {
    return (
      <main className="flex min-h-screen items-center justify-center px-6">
        <div className="max-w-md text-center">
          <p className="font-display text-xl font-semibold text-ink">Something went wrong</p>
          <p className="mt-2 text-[14.5px] text-ink-soft">{fetchState.message}</p>
          <a
            href="/"
            className="mt-6 inline-flex items-center gap-2 rounded-xl bg-ink px-4 py-2.5 text-[14px] font-medium text-paper"
          >
            Try another repo
          </a>
        </div>
      </main>
    );
  }

  // Wait for both the animation AND the fetch before showing the result
  if (!animDone || fetchState.status === "loading") {
    return <LoadingScreen repo={slug} onDone={() => setAnimDone(true)} />;
  }

  return <Onboarding data={fetchState.data} />;
}
